name: Build, Test, and Push QR Code Generator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # 1️⃣ Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # 4️⃣ Run tests with coverage
      - name: Run tests
        run: |
          pytest -v --cov=main --cov-report=term-missing --cov-report=xml

      # 5️⃣ Upload coverage reports (optional but recommended)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: always()
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: test  # This job runs only after tests pass
    if: github.event_name == 'push'  # Only build/push on push, not PR

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/qr_code_generator:latest .

      # 5️⃣ Test run container to verify it works
      - name: Run container test
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/qr_code_generator:latest --url https://www.njit.edu

      # 6️⃣ Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/qr_code_generator:latest

      # 7️⃣ Tag with git commit SHA (optional but best practice)
      - name: Tag and push with commit SHA
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/qr_code_generator:latest \
            ${{ secrets.DOCKERHUB_USERNAME }}/qr_code_generator:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/qr_code_generator:${{ github.sha }}